### ISSUE TITLE
Sub-menu overlap - Chrome & Firefox

### ISSUE THREAD

**Issue by jonathanbardo** [godaddy/wp-velux-theme#21]
![screen shot 2016-08-09 at 12 16 06 pm](https://cloud.githubusercontent.com/assets/1933681/17524112/2d3e5e7e-5e2b-11e6-8403-97d5c3f7d48a.png)

**Comment by mrpritchett** [comment]
@jonathanbardo Is this Windows? Also, what resolution are you seeing this?

**Comment by jonathanbardo** [comment]
@mrpritchett I've tested this on a mac using latest Chrome & Firefox on a 1920x1200px monitor.

**Comment by mrpritchett** [comment]
@jonathanbardo Please confirm this is fixed at http://liftux.wpengine.com/velux/
![screen shot 2016-08-09 at 1 25 08 pm](https://cloud.githubusercontent.com/assets/3329081/17526321/b766e982-5e34-11e6-9004-3b2302c9ef0a.png)

**Comment by jonathanbardo** [comment]
@mrpritchett All good now. Thank you!
