### ISSUE TITLE
Mobile menu is missing a background

### ISSUE THREAD

**Issue by jonathanbardo** [godaddy/wp-velux-theme#27]
![screen shot 2016-08-18 at 9 49 33 am](https://cloud.githubusercontent.com/assets/1933681/17776095/20c5e7fc-6529-11e6-9d5a-1f99c5a67d52.png)

**Comment by chriswallace** [comment]
Fixed in 24c9583558f26a0be8ac76d6bb9b3cc9d43b6bc3
