### ISSUE TITLE
Borders should not appear when hovering on mobile nav

### ISSUE THREAD

**Issue by fjarrett** [godaddy/wp-velux-theme#28]
<img width="79" alt="screen shot 2016-08-26 at 2 44 33 pm" src="https://cloud.githubusercontent.com/assets/522158/18018291/99114c88-6b9b-11e6-8b74-a1295576f965.png">

<img width="343" alt="screen shot 2016-08-26 at 2 43 45 pm" src="https://cloud.githubusercontent.com/assets/522158/18018278/90db95c8-6b9b-11e6-8af8-59916f9cbb2d.png">

**Comment by mrpritchett** [comment]
Just to be clear, are we talking about the mobile nav on a desktop? Or perhaps first click on a mobile device? Otherwise, I want to see this "hover" on a mobile device. ;)

**Comment by chriswallace** [comment]
I believe this is also caused by [this issue](https://github.com/godaddy/wp-ascension-theme/issues/48). @fjarrett What are your thoughts here?

**Comment by fjarrett** [comment]
@chriswallace Decided to use a `:not(.open)` selector, which is only seen on mobile.
