### ISSUE TITLE
No Option To Change The Copyright Section

### ISSUE THREAD

**Issue by MediaMillenniaSEO** [godaddy/wp-velux-theme#36]
I like the cleanliness of the velux theme but I do not see the option to change the wording for the copyright. Not even with an installed plug in. I explored youtube, read articles spent more than 4 hours trying to figure out from the editor of the theme section to no avail. I would like to know how to change it and would appreciate your advice before I will have to replace it with another theme that has that option. Thank you for your time.

**Comment by fjarrett** [comment]
Hi @MediaMillenniaSEO! We've receive a lot of feedback on this and will be updating the Primer parent theme soon to make this much easier.

Just to clarify, are you talking about this text?

<img width="343" alt="screen_shot_2017-02-13_at_2_30_31_pm" src="https://cloud.githubusercontent.com/assets/522158/22901998/2fc0401a-f1f9-11e6-92e1-d1aef20f46ca.png">

**Comment by MediaMillenniaSEO** [comment]
Yes, that's what I meant. What is your projected time-frame? I resorted to calling GoDaddy about this as Velux is branded as GoDaddy's theme, but no one was able to help. I would appreciate if you give me a heads up when that is taken cared of on this thread. Thank you much!

**Comment by fjarrett** [comment]
@MediaMillenniaSEO the feature is actually being tracked in the parent theme (Primer), I'd suggest heading over and clicking "Subscribe" on this issue https://github.com/godaddy/wp-primer-theme/issues/155
