### ISSUE TITLE
Random Line Of Code Appears On Every Page of this Velux Theme

### ISSUE THREAD

**Issue by ckoerner87** [godaddy/wp-velux-theme#45]
My site is liahonahomebuilders.com. If you look closely within the header image on each page you'll see a line or two of code in dark gray front that looks like this across the bottom of the pic:
 
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'primer_video_header' not found or invalid function name in /home/content/a2pewpnas01_data02/42/4014542/html/wp-includes/class-wp-hook.php on line 298
 
Some variation of this is in the same place on every page.
 
I thought it was a plugin problem, but when I deactivated all the plugins it was still there. I use this theme on another WP site as well (betterexit.com) and do not have this issue.
 
So what could it be? Please help!

**Comment by EvanHerman** [comment]
Hi @ckoerner87 ,

What version of Primer do you have installed? Have you updated to version 1.7.0?

**Comment by ckoerner87** [comment]
You are the man! Thank you so much. I was on 1.6.0 of Primer, I updated it and now I'm good. 

One more question and then I should be all set:

As you can see in the screenshot below, the mobile responsiveness of the hamburger menu (top right) is a bit wonky. It conflicts with my headline/logo. How do I fix this?

![image](https://cloud.githubusercontent.com/assets/28056223/25440677/c1d06f12-2a65-11e7-8427-2f925b3363a1.png)

Also, along the same lines of mobile responsiveness, when I use the menu to go to other pages, the headline of that page overlaps the drop down menu like this:

![image](https://cloud.githubusercontent.com/assets/28056223/25440731/e9cae704-2a65-11e7-886d-ce03e0d96033.png)

Any idea of how to fix those two responsiveness/overlap issues?

Thank you so much for the help so far!

**Comment by EvanHerman** [comment]
Hi there @ckoerner87,

To resolve the overlapping issue, you'll need to tweak the z-index CSS declaration on the `.page-title-container .page-header` element. The following should fix things for you:

```css
.page-title-container .page-header {
   position: inherit;
}
```
I'm not sure why this is overlaying on top of the dropdown menu, this is something we'll have to take a look into.

As for the overlapping text, you should be able to tweak the width of the site title container to get it looking right. I do see what you are talking about on my phone as well, it looks like the site title is overflowing outside of the container and overlapping over the menu button. Give the following a try:

```css
.site-title-wrapper {
   width: 80%;
}
```

**Comment by ckoerner87** [comment]
That fixed all of my problems! Thank you so much.

**Comment by EvanHerman** [comment]
@ckoerner87 No problem at all - we will have a look into the z-indexing problem with the menu/title.

Have a great day!
