### ISSUE TITLE
drop down menu disappears with mouse over, but not on home page

### ISSUE THREAD

**Issue by MarthaRidgeway** [godaddy/wp-velux-theme#49]
I am a novice WordPress user working on the GoDaddy theme Velux, which is a child of Primer. The Portfolio drop down menu only works on the Home Page. On all other pages, the Portfolio drop down menu disappears when you mouse over over the list. I am running Velux 1.1.0 and Primer 1.7.0. Here is the temporary URL that GoDaddy gave me: http://870.0b0.myftpupload.com. I am also having the exact same troubles described in Issues #48 and #46. But when I add the suggested code to "Additional CSS," nothing changes.  Any help would be greatly appreciated.

**Comment by EvanHerman** [comment]
Hi @MarthaRidgeway ,

Do you still have the theme installed? It looks like the stylesheet is not loading, and the page is a bit jumbled.

Additionally, are you referring to the CSS code found here?
https://github.com/godaddy/wp-velux-theme/issues/45

This code is currently awaiting review here in a pull request https://github.com/godaddy/wp-velux-theme/pull/47. I can take a look at this and get it merged in. We are currently prepping a new Primer release, v1.7.1. If need be we can also release a patch here for Velux with the changes listed in the issues and PR you have mentioned.

Best,
Evan

**Comment by EvanHerman** [comment]
Hi @MarthaRidgeway,

After a quick review, it does in fact look like these issues are going to be resolved when we get the pull request listed above (issue #47) merged in.

I will review the pull request and get things merged in so when we release Primer 1.7.1 in the coming days, we can also release a new version of Velux with these fixes.

Best,
Evan

**Comment by EvanHerman** [comment]
Hi @MarthaRidgeway 

I've gone ahead and reviewed the two outstanding pull requests which resolve the issue you mentioned. They are currently sitting on the develop branch of this repository.

You can either download the .zip right from here on GitHub:

[Velux (Development Branch)](https://github.com/godaddy/wp-velux-theme) - [Download Link](https://github.com/godaddy/wp-velux-theme/archive/develop.zip)

or you can wait until we release the v1.1.1 patch for Velux.

Either way, once you have 1.1.1 installed on your site the issue should be resolved. It is worth noting that on the `develop` branch, the version is still set to 1.1.0 as we haven't bumped the version just yet (we do it on release), but the changes are in there.

I will certainly post back here a second time when we've gone ahead and got the new version released.

Best,
Evan

**Comment by MarthaRidgeway** [comment]
Good morning!

Oh this is excellent news! One last question: I downloaded the ZIP file but I don’t know what to do with it. (I am on a Mac and my theme is running in Safari from GoDaddy.com <http://godaddy.com/>.) Where do I put these files?

Thank you so much!



 <http://californiadpm.com/>	
Martha Ridgeway / Graphic Designer 
mridgeway@cal-litho.com <mailto:mridgeway@cal-litho.com>
California Design, Printing & Marketing 
Office: 909.305.8800 / Fax: 909.305.8801 
456 S. San Dimas Ave. / San Dimas, CA 91773 
californiadpm.com <http://californiadpm.com/>
 <https://www.facebook.com/CaliforniaDPM>  <https://plus.google.com/100043395971618712029/posts?hl=en>  <https://www.linkedin.com/company/california-design-printing-&-marketing>  <https://www.youtube.com/channel/UCWgE24oYLBSVtc-d1osmd7A>  <http://www.yelp.com/biz/california-design-printing-and-marketing-san-dimas?ytprail=1>

**Comment by EvanHerman** [comment]
Hi @MarthaRidgeway,

If you downloaded the .zip from the link above - you will want to remove `-develop` from the file name. Then all you have to do is upload the theme to your site. You can do so from 'Appearance > Themes' and clicking the 'Add New' link at the top.

If you are unable to FTP into the server, or are unfamiliar how to do so, you will have to delete the existing theme. If you don't first delete the existing velux theme, you will encounter an error.

If you _can_ FTP into your server, you can just upload the files from within the .zip archive into the existing `velux` directory inside of `wp-content/themes/`.

Otherwise I would recommend holding off until we release the new patch, so you can just update the existing theme from within your site dashboard.

Best,
Evan

**Comment by MarthaRidgeway** [comment]
Got it!

Thank you so much!



 <http://californiadpm.com/>	
Martha Ridgeway / Graphic Designer 
mridgeway@cal-litho.com <mailto:mridgeway@cal-litho.com>
California Design, Printing & Marketing 
Office: 909.305.8800 / Fax: 909.305.8801 
456 S. San Dimas Ave. / San Dimas, CA 91773 
californiadpm.com <http://californiadpm.com/>
 <https://www.facebook.com/CaliforniaDPM>  <https://plus.google.com/100043395971618712029/posts?hl=en>  <https://www.linkedin.com/company/california-design-printing-&-marketing>  <https://www.youtube.com/channel/UCWgE24oYLBSVtc-d1osmd7A>  <http://www.yelp.com/biz/california-design-printing-and-marketing-san-dimas?ytprail=1>

**Comment by tussinglady** [comment]
Ok so I installed the new theme because I was having this EXACT problem. But now my home page is different? Instead of the HUGE picture that said "Make a Bold Statement", it's just a smaller version and that text is gone. What happened?
