### ISSUE TITLE
Update path for Velux installs

### ISSUE THREAD

**Issue by lukefivedev** [godaddy/wp-velux-theme#53]
We have two Velux installs. One installed long before I started with this company. The other I installed from zip file downloaded here at Github. We're noticing issues with older install, plus file/directory structure different between two installs. What is correct update for older client install? GoDaddy tech support insists we should search themes at wordpress.org but Velux not there only Primer. WordPress admin panel not showing any pending updates.

**Comment by EvanHerman** [comment]
Hi @lukefivedev,

What is different in the directory structure? It sounds like you may have customize the original Velux theme a bit. To properly update an existing site with a new version hosted here on Github, you can download the .zip archive from the [releases tab](https://github.com/godaddy/wp-velux-theme/releases/tag/v1.1.0) (here on GitHub) and upload the contents via FTP to your server (making sure to overwrite all of the existing files).

At the moment we have [Primer](https://wordpress.org/themes/primer/) and [Activation](https://wordpress.org/themes/activation/) up on WordPress.org, and we are working on getting the rest of our themes hosted there as well.

**Comment by lukefivedev** [comment]
The newer version from Github has directories not in the older install, for example a js directory inside assets. I have only customized the CSS and functions.php. I will backup our site then use the steps you describe here.

**Comment by lukefivedev** [comment]
The problem remains after these steps and being sure to clear the cache. On smartphones, clicking the 'hamburger' does not display the mobile-only version of navigation. Have tried using Chrome dev tools to diagnose this. Here's a link to malfunctioning site...  [http://luke5marketing.com/](url)

**Comment by EvanHerman** [comment]
Hi @lukefivedev 

There should be no js directory inside of the assets folder. There is no history of any js directory existing there. If you download the latest version and overwrite what you have, that directory should no longer exist.

You can try downloading the version we have setup on the `develop` branch [here](https://github.com/godaddy/wp-velux-theme/archive/develop.zip).
https://github.com/godaddy/wp-velux-theme/tree/develop

There were a few bugs that were reported that we have merged into the develop branch but have not yet merged into master.
https://github.com/godaddy/wp-velux-theme/issues/51
https://github.com/godaddy/wp-velux-theme/issues/49

You'll also want to make sure you are using the latest version of Primer.

After you instal the latest version of Velux you may want to try disabling Auto Optimize before re-testing.

Other than running the development branch version of Velux my recommendation would be to hold off until we have the new version released.

**Comment by okieman** [comment]
I got this much done. But I still have one Velux site where the mobile hamburger calls up navigation and another site where it does not. My boss is not happy. Can you tell me this function is CSS-only? If there is no JavaScript involved, then I will debug this as an HTML/CSS problem only. Thx.

**Comment by EvanHerman** [comment]
Hi @okieman 

There is JavaScript involved. When the hamburger menu is clicked an 'open' class is added to the menu.

https://github.com/godaddy/wp-primer-theme/blob/develop/assets/js/navigation.js#L9-L15

**Comment by okieman** [comment]
Both sites seem to call that script in the header. One difference. The functioning site appends a variable. Not sure if this matters... `/wp-content/themes/primer/assets/js/navigation.min.js?ver=1.8.0'`

**Comment by EvanHerman** [comment]
That shouldn't be an issue. That is just referencing the version of the parent theme, [Primer](https://wordpress.org/themes/primer/).

Have you tried disabling your plugins to see if that resolves the issue? Are you encountering any sort of javascript error on the site? Do you have a link to both sites?

**Comment by okieman** [comment]
Only the broken site is public. When I use Chrome inspector, it's obvious the script is not getting called, because the '.open' never happens. If a plugin is the problem, then it is most likely one of the caching tools to increase our page speed score. I'll be out for several hours but here is the link...  [http://luke5marketing.com/](url)

**Comment by okieman** [comment]
Fixed. Long story short; the tools that help me shuffle CSS and JS around to please Google PageSpeed come with their own problems. Thank you @EvanHerman for the weekend tech support.
