### ISSUE TITLE
Sub menu is not working correctly

### ISSUE THREAD

**Issue by eagle7corps** [godaddy/wp-velux-theme#60]
On http://energiapyramiid.ee/osta/ the sub menu is not working... As soon the mouse is dragged to the sub-menus it disappears... Although on the homepage of this website, I'm not having this issue...

**Comment by EvanHerman** [comment]
Hi @eagle7corps 

What version of Primer do you have installed? I would also suggest updating Velux to version 1.1.1.
https://github.com/godaddy/wp-velux-theme/releases/tag/v1.1.1

**Comment by eagle7corps** [comment]
Hey @EvanHerman, Thanks a lot man.... I updated primer but there was no update for Velux shown... so, thanks for giving the link for new version...
It solved that problem but caused other problem, which I fixed with some custom code. And no, I was not using any custom code before.... 
The custom code I used to fix the new problem is: 
.site-title-wrapper {
    padding-top: 0;
    text-align: left;
    width: 0%;
}
Thanks for the help Bro... 👍

**Comment by EvanHerman** [comment]
@eagle7corps No problem at all - I'm glad that the new version helped alleviate the issue and that I could jump in and help out.

If you run into any other issues or encounter anything strange going on, feel free to drop us a line and we'll investigate.

Have a great rest of your day!
