### ISSUE TITLE
Social media icons in header area?? How to add?

### ISSUE THREAD

**Issue by team2win** [godaddy/wp-velux-theme#66]
I noticed there is supposedly a way to add social media icons to the header area, I was trying to add it on the same line as title or above menu. Does anyone know how this can be done?

Thank you

**Comment by EvanHerman** [comment]
@team2win 

There is nothing built into the plugin to allow for social media icons in the header area (out of the box). Where did you see that example? You can most certainly install our plugin [ContactWidgets](https://wordpress.org/plugins/contact-widgets/) and add the social icons widget to your header. In that case, the social media icons would then appear up in the header as you have proposed.

Evan

**Comment by team2win** [comment]
Hello, I didn't see an example of it being in header area, the 
Primary Menu area shows social menu that can be added, I thought primary menu was the top menu, so when you add it, I thought it would add to the primary menu up top. This is not the case I guess. I was looking to add above the Menu names, but seems not possible? As of now, the icons are at the bottom of the page out of sight.
