### ISSUE TITLE
Need logo AND Site Title AND Tagline to appear.

### ISSUE THREAD

**Issue by benjaminalexanderdemers** [godaddy/wp-velux-theme#67]
Hi Evan, Great theme.  Just one thing.  How do I get the logo, the site title and the tagline to appear together?  I have checked the box in the customizer but it does not appear.  It only appears when I remove the logo.  Please help!  CSS for Additional CSS is fine.  I can do that cut and paste.

Thanks,

Benjamin De Mers

**Comment by EvanHerman** [comment]
Hi @benjaminalexanderdemers 

I just did a quick test and it does look like the logo I have set, the site title and tagline are all appearing. Do you have a link to your site? I can take a look and see if I can spot anything from the frontend.

Evan
