### ISSUE TITLE
Button Background Color DOES NOT change with color picker or manual selection.  Remains orange-ish brown YUCK

### ISSUE THREAD

**Issue by benjaminalexanderdemers** [godaddy/wp-velux-theme#68]
Using Beaver Builder with Godaddy installation of WordPress and Velux theme selection.  Beaver Builder does not change the button color of the call to action button.  Remains the stock color, whatever that is, and it ain't pretty.  What can be done?  Evan?

Help meeee!

**Comment by EvanHerman** [comment]
Hi @benjaminalexanderdemers 

Are you referring to the call to action up in the header? You should be able to adjust that using the Customizer controls contained within the theme. From the dashboard if you navigate to 'Appearance > Customize > Colors > Buttons' you should be able to tweak the colors of the call to action buttons or other areas of the theme.

Let us know if that helps!

Evan
