### ISSUE TITLE
Removing header image overlay in Velux

### ISSUE THREAD

**Issue by emrock55** [godaddy/wp-velux-theme#69]
I'd like to remove or lighten the transparent overlay on the header image in Velux and I'm new to CSS. Help!

**Comment by EvanHerman** [comment]
Hi @emrock55 

You can adjust the background color overlay inside of the customizer. From the dashboard if you head into **Appearance > Customize** and then direct yourself to **Colors > Header**, the last option there will be slider titled **Hero Background Overlay**.

<img title="Hero Background Overlay" src="https://cldup.com/K0lmEIh6Fi.png" width="40%" />

You can slide the slider all the way to the left to remove the overlay color completely, or slide it where you need it.

Let us know if that helps!

**Comment by emrock55** [comment]
Thank you for the speedy response!
