### ISSUE TITLE
Override Featured Image on PAGE Header - Not Post Header

### ISSUE THREAD

**Issue by millennia2** [godaddy/wp-velux-theme#75]
In the customizer there is the option to use, or not to use, the featured image for the header on **posts**, but not for **pages**, which I have unchecked as to not use the featured image for the header. However, this option does not seem to affect the pages, only the posts. 

I need to use the featured images on product pages for various widgets across the site, but I do not want my pages to have the featured image as the header - I would like to keep the main header on all pages and posts. Any suggestions would be much appreciated!

Home Page with main (correct) header: http://jxj.70a.myftpupload.com

Product Page with Featured Image header (which I do not want): http://jxj.70a.myftpupload.com/products/residential-accessories/819lm-myq-home-bridge/

Thank you!

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
