### ISSUE TITLE
Flyout Menu Issues

### ISSUE THREAD

**Issue by Twofebboys** [godaddy/wp-velux-theme#76]
I am having trouble with the Velux theme from Elementor on Wordpress. The flyout menu is kicking it off to the right side of the screen instead of the left and you can't read it on the screen without scrolling to the right. Is there some way to fix this?

![Capture](https://user-images.githubusercontent.com/53525302/62214782-b7eec400-b373-11e9-810e-4d0d44e77505.jpg)

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
