### ISSUE TITLE
How to build the homepage, like in the demo?

### ISSUE THREAD

**Issue by IonicaBizau** [godaddy/wp-velux-theme#77]
The [Demo Screenshot](https://wordpress.org/themes/velux/) looks nice, but I have a hard time implementing it on my website.

 - How do I add that big text over the header image?
 - How do I add the link etc?
 - How do I add the Services section?

I understand this is a child theme of Primer, but I can't find any docs regarding that either...

Thanks!

**Comment by ghost** [comment]
hi, i follow it, did you find a way ?

**Comment by EvanHerman** [comment]
Hi @IonicaBizau 

The big text over the header image is the hero text widget. Inside of the widgets section in the dashboard you should see a section titled 'Hero'. You can add the 'Hero Text' widget there and add the needed text.

![image](https://user-images.githubusercontent.com/5321364/66325270-f0bb9400-e8f4-11e9-9330-cbaa303cdcaf.png)

![image](https://user-images.githubusercontent.com/5321364/66325377-26f91380-e8f5-11e9-8df0-63ef916a016a.png)

As for the services section, it would be easiest to install https://wordpress.org/plugins/coblocks/ and use the 'Row Block' to create a 3 column row, to easily replicate that layout.

Let us know if that helps!

**Comment by IonicaBizau** [comment]
@EvanHerman Thank you! Is it coblocks what it's used in the demo?

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
