### ISSUE TITLE
Logo not aligning with menu

### ISSUE THREAD

**Issue by Swens6** [godaddy/wp-velux-theme#78]
When I load my logo under "customizing site identity", it ends up being pushed to the top of my header with the menu remaining in the middle of the header.  So my logo on the left side of the header sits higher than my menu on the right side (see pic).

If I type into the "Site Title and Tagline" categories, it remains aligned with the menu... exactly how it should be.

I have read that you can decrease the header padding and that should help, but the css code I have found to put into the  "additional CSS" field to reduce the padding does nothing.

I can't find a way to get to the header padding through any of the customize menus.

Can anyone help me with a fix? 

![Site Issue](https://user-images.githubusercontent.com/54331413/63378055-febe5100-c356-11e9-9266-f2298446f036.JPG)

**Comment by elbarre** [comment]
Hello, have you solve that? I have the same problem

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
