### ISSUE TITLE
Not able to find footer "copyright @2019"

### ISSUE THREAD

**Issue by Developdev** [godaddy/wp-velux-theme#79]
Hi,

I want to remove copyright from the footer but not able to locate this code anywhere, usually this text we find in footer.php or footer.html/etc, I've tried everything but still empty-handed. 

Thanks 

![Capture](https://user-images.githubusercontent.com/55386981/64950570-51792300-d899-11e9-9184-cdddcd5f25cb.PNG)

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
