### ISSUE TITLE
Issue with  .main-navigation .expand color of '+' is obscured test

### ISSUE THREAD

**Issue by pm99** [godaddy/wp-velux-theme#92]
Hello,
(site: oraclejiujitsu.com)

I find that Velux '+' mobile menu expand icon ('+') is obscured because (I believe) the background color is dark grey and (I think) transparent (?) so the '+' icon is grey-looking and barely perceptible.

I'm not a css expert, and after an hour of fiddling around, I was still lost.

Please see attached screen shot where the dark '+' is hidden (in the after expand state of course it's a '-').

![Screen Shot 2021-03-31 at 2 40 47 PM](https://user-images.githubusercontent.com/1196650/113194647-590bdd00-922f-11eb-957b-5cdcc6517db6.png).

Any help would be greatly appreciated.
Thanks in advance.
Lee

test edit aug5

**Comment by pm99** [comment]
Hello? Am I in the right place to post issues with Godaddy supported issues with velux theme?

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
